### ISSUE TITLE
Use a more robust hashing method

### ISSUE THREAD

**Issue by guillaumevincent** [dotcypress/password#3]
Your algorithm use md5 to build your hash.
md5 is not good because it's fast. An attacker can try billions of passwords per second on a single GPU. (see http://hashcat.net/hashcat/).

If one database leak, with passwords generated with your tool, it will take a couple of hours to find one master password < 14 chars.

Disclaimer: I'm the creator of LessPass, another stateless password manager.
You can see the current algorithm used by LessPass: we use pbkdf2 100k iterations: https://github.com/lesspass/core/blob/master/src/v2.js

**Comment by dotcypress** [comment]
Thank you @guillaumevincent 

Switched to `PBKDF2`
